### ISSUE TITLE
problem about octree constuction

### ISSUE THREAD

**Issue by xuyiqun** [RufaelDev/pcc-mp3dg#3]
I am not clear where the octree is constructed or where the parameter octree bit setting is used in octree construction. Maybe it is a stupid question, but I really want to know more details about the project. Thank you

**Comment by xuyiqun** [comment]
that the octree bit setting is 11 equals to that the octree depth is define to 11 or 12?  The value is 0 mean the root node is partitioned to 8 nodes?

**Comment by RufaelDev** [comment]
dear xuyin, the bounding box is normalized to 0...1 intervals, the bitsetting is converted to floating point point precision used by the PCL octree code. see compression_eval_impl.hpp the function generatePCLOctreeCodecV2 for the details. So internally the bitsetting is not used you were right about that. Kind Regards, Rufael

**Comment by xuyiqun** [comment]
Thank you
